version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  test-database:
    docker:
      - image: circleci/node:12.16.2
        environment:
          DATABASE_SQL_HOST: localhost
          DATABASE_SQL_USERNAME: fwl_db
          DATABASE_SQL_PASSWORD: fwl_db
          DATABASE_SQL_PORT: 5432
          DATABASE_SQL_DATABASE: fwl_db
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: fwl_db
          POSTGRES_PASSWORD: fwl_db
          POSTGRES_DB: fwl_db
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: database-tests
          command: yarn test
          working_directory: packages/database

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - test-database:
          requires:
            - setup
