version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
  test-database:
    docker:
      - image: circleci/node:12.16.2
        environment:
          DATABASE_SQL_HOST: localhost
          DATABASE_SQL_USERNAME: fwl_db
          DATABASE_SQL_PASSWORD: fwl_db
          DATABASE_SQL_PORT: 5432
          DATABASE_SQL_DATABASE: fwl_db
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: fwl_db
          POSTGRES_PASSWORD: fwl_db
          POSTGRES_DB: fwl_db
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: database-tests
          command: yarn --cache-folder ~/.cache/yarn test
          working_directory: packages/database
  test-logging:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: logging-tests
          command: yarn --cache-folder ~/.cache/yarn test
          working_directory: packages/logging
      - run:
          name: logging-lint
          command: yarn --cache-folder ~/.cache/yarn lint
          working_directory: packages/logging
  test-migration:
    docker:
      - image: circleci/node:12.16.2
        environment:
          DATABASE_SQL_HOST: localhost
          DATABASE_SQL_USERNAME: fwl_db
          DATABASE_SQL_PASSWORD: fwl_db
          DATABASE_SQL_PORT: 5432
          DATABASE_SQL_DATABASE: fwl_db
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: fwl_db
          POSTGRES_PASSWORD: fwl_db
          POSTGRES_DB: fwl_db
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: migrate-tests
          command: yarn --cache-folder ~/.cache/yarn test
          working_directory: packages/migration
  test-tracing:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: tracing-tests
          command: yarn --cache-folder ~/.cache/yarn test
          working_directory: packages/tracing
      - run:
          name: tracing-lint
          command: yarn --cache-folder ~/.cache/yarn lint
          working_directory: packages/tracing
  test-web:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: web-lint
          command: yarn --cache-folder ~/.cache/yarn lint
          working_directory: packages/web


workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - test-database:
          requires:
            - setup
      - test-logging:
          requires:
            - setup
      - test-migration:
          requires:
            - setup
      - test-tracing:
          requires:
            - setup
      - test-web:
          requires:
            - setup
