version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v5-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-v5-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

  test-database:
    docker:
      - image: circleci/node:16.13.1
        environment:
          DATABASE_SQL_HOST: localhost
          DATABASE_SQL_USERNAME: fwl_db
          DATABASE_SQL_PASSWORD: fwl_db
          DATABASE_SQL_PORT: 5432
          DATABASE_SQL_DATABASE: fwl_db
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: fwl_db
          POSTGRES_PASSWORD: fwl_db
          POSTGRES_DB: fwl_db
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v5-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: database-tests
          command: yarn lerna run --scope @fwl/database test

  test-logging:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v5-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: logging-tests
          command: yarn lerna run --scope @fwl/logging test
          working_directory: packages/logging
      - run:
          name: logging-lint
          command: yarn lerna run --scope @fwl/logging lint

  test-migration:
    docker:
      - image: circleci/node:16.13.1
        environment:
          DATABASE_SQL_HOST: localhost
          DATABASE_SQL_USERNAME: fwl_db
          DATABASE_SQL_PASSWORD: fwl_db
          DATABASE_SQL_PORT: 5432
          DATABASE_SQL_DATABASE: fwl_db
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: fwl_db
          POSTGRES_PASSWORD: fwl_db
          POSTGRES_DB: fwl_db
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v5-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: migrate-tests
          command: yarn lerna run --scope @fwl/migration test

  test-tracing:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v5-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: tracing-tests
          command: yarn lerna run --scope @fwl/tracing test
      - run:
          name: tracing-lint
          command: yarn lerna run --scope @fwl/tracing lint

  test-web:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v5-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: web-lint
          command: yarn lerna run --scope @fwl/web lint

  build-migration-image:
    machine:
        image: ubuntu-2204:2022.04.1
        docker_layer_caching: true
    steps:
      - checkout
      - run: docker login -u ${DOCKER_USERNAME} -p $(echo ${DOCKER_PASSWORD} | base64 --decode)
      - run:
          command: ../bin/build-and-push.sh fwl-migration $CIRCLE_REPOSITORY_URL $CIRCLE_BRANCH $CIRCLE_SHA1
          working_directory: migration

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - test-database:
          requires:
            - setup
      - test-logging:
          requires:
            - setup
      - test-migration:
          requires:
            - setup
      - test-tracing:
          requires:
            - setup
      - test-web:
          requires:
            - setup
      - build-migration-image:
          requires:
            - test-migration
