version: 2.1
jobs:
  test-database:
    docker:
      - image: circleci/node:16.13.1
        environment:
          DATABASE_SQL_HOST: localhost
          DATABASE_SQL_USERNAME: fwl_db
          DATABASE_SQL_PASSWORD: fwl_db
          DATABASE_SQL_PORT: 5432
          DATABASE_SQL_DATABASE: fwl_db
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: fwl_db
          POSTGRES_PASSWORD: fwl_db
          POSTGRES_DB: fwl_db
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/database/yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile
          working_directory: packages/database
      - save_cache:
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/database/yarn.lock" }}
          paths:
            - "packages/database/node_modules"
      - run:
          name: database-tests
          command: yarn test
          working_directory: packages/database
  test-logging:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/logging/yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile
          working_directory: packages/logging
      - save_cache:
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/logging/yarn.lock" }}
          paths:
            - "packages/logging/node_modules"
      - run:
          name: logging-tests
          command: yarn test
          working_directory: packages/logging
      - run:
          name: logging-lint
          command: yarn lint
          working_directory: packages/logging
  test-migration:
    docker:
      - image: circleci/node:16.13.1
        environment:
          DATABASE_SQL_HOST: localhost
          DATABASE_SQL_USERNAME: fwl_db
          DATABASE_SQL_PASSWORD: fwl_db
          DATABASE_SQL_PORT: 5432
          DATABASE_SQL_DATABASE: fwl_db
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: fwl_db
          POSTGRES_PASSWORD: fwl_db
          POSTGRES_DB: fwl_db
    steps:
      - checkout
      - restore_cache:
          keys:
            - migrations-yarn-packages-v2-{{ .Branch }}-{{ checksum "migrations/yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile
          working_directory: migration
      - save_cache:
          key: migrations-yarn-packages-v2-{{ .Branch }}-{{ checksum "migrations/yarn.lock" }}
          paths:
            - "migrations/node_modules"
      - run:
          name: migrate-tests
          command: yarn test
          working_directory: migration
  test-tracing:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/tracing/yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile
          working_directory: packages/tracing
      - save_cache:
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/tracing/yarn.lock" }}
          paths:
            - "packages/tracing/node_modules"
      - run:
          name: tracing-tests
          command: yarn test
          working_directory: packages/tracing
      - run:
          name: tracing-lint
          command: yarn lint
          working_directory: packages/tracing
  test-web:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/web/yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install --frozen-lockfile
          working_directory: packages/web
      - save_cache:
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "packages/web/yarn.lock" }}
          paths:
            - "packages/web/node_modules"
      - run:
          name: web-lint
          command: yarn lint
          working_directory: packages/web
  build-migration-image:
    machine:
        image: ubuntu-2204:2022.04.1
        docker_layer_caching: true
    steps:
      - checkout
      - run: docker login -u ${DOCKER_USERNAME} -p $(echo ${DOCKER_PASSWORD} | base64 --decode)
      - run:
          command: ../bin/build-and-push.sh fwl-migration $CIRCLE_REPOSITORY_URL $CIRCLE_BRANCH $CIRCLE_SHA1
          working_directory: migration



workflows:
  version: 2
  build-and-test:
    jobs:
      - test-database
      - test-logging
      - test-migration
      - test-tracing
      - test-web
      - build-migration-image:
          requires:
            - test-migration
