version: "2.1"

services:  
  jaeger:
    image: jaegertracing/all-in-one:1.20.0
    command: ["--collector.zipkin.http-port=29995", "--log-level=debug"]
    ports:
      - "29798:6831/udp"
      - "29797:16686"
      - "29796:14268"
      - "29795:14250"

  opentelemetry_collector:
    image: otel/opentelemetry-collector:0.18.0
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=debug"]
    depends_on:
      - jaeger
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "29799:55681"
