version: "2.1"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.20.0
    command: ["--log-level=debug"]
    ports:
      - "21097:6831/udp"
      - "21096:16686"
      - "21095:14268"
      - "21094:14250"

  opentelemetry_collector:
    image: otel/opentelemetry-collector:0.18.0
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=debug"]
    depends_on:
      - jaeger
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "21098:55681"